version: '3'

services:
  db:
    image: postgres
    volumes: 
      - './tmp/db:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: pw1234
  web:
    depends_on: 
      - 'db'
    build: .
    volumes:
      - .:/portal-solar-dev-test
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    links:
      - db

volumes:
  postgres: